In [25]:
import pandas as pd
url = 'https://s3.amazonaws.com/orim-misc-data/assessment/subscribers.csv'
dataset = pd.read_csv(url)
dataset["Signup"] = pd.to_datetime(dataset["Signup"])

In [50]:
filtered_df = pd.DataFrame()
filtered_df["Signup_year"] = dataset["Signup"].dt.year
filtered_df["Signup_month"] = dataset["Signup"].dt.month
filtered_df["referral_source"] = dataset["referral_source"]
filtered_df

        Signup_year  Signup_month  referral_source
0              2015             6              DMi
1              2014            10         Untagged
2              2016             2              DMi
3              2016             9         Facebook
4              2014            12              NaN
5              2016            10       In Book Ad
6              2016             5       LiveIntent
7              2015             9              DMi
8              2014            10         Untagged
9              2014            11         Facebook
10             2014            12         Facebook
11             2016            12              NaN
12             2015            10       In Book Ad
13             2015            12              DMi
14             2014             8         Untagged
15             2016             1              DMi
16             2017             2       LiveIntent
17             2016             1              DMi
18             2016             1              DMi
19             2014             8         Untagged
20             2016             3       LiveIntent
21             2016             1       In Book Ad
22             2015             4  Permission Data
23             2017             4        torsweeps
24             2016             7       LiveIntent
25             2016            12       LiveIntent
26             2014            12         Facebook
27             2016             4   BookRiotSweeps
28             2014            10         Untagged
29             2016            12           Google
...             ...           ...              ...
705114         2014             9         Untagged
705115         2016             1              DMi
705116         2015             7              DMi
705117         2014             9         Untagged
705118         2015             8              DMi
705119         2015             8              DMi
705120         2015             9              DMi
705121         2016            12   BookRiotSweeps
705122         2015             8              DMi
705123         2015             7              DMi
705124         2015             9              DMi
705125         2015             8              DMi
705126         2015            12              DMi
705127         2015             8              DMi
705128         2016            10       In Book Ad
705129         2016             1              DMi
705130         2015             1         Facebook
705131         2015             8              DMi
705132         2015             8              DMi
705133         2016             1       LiveIntent
705134         2015             9              DMi
705135         2017             4              NaN
705136         2016             6       In Book Ad
705137         2014             9         Untagged
705138         2015            10         Facebook
705139         2015             7              DMi
705140         2015             9              DMi
705141         2015             9              DMi
705142         2016             5              NaN
705143         2015             6              DMi

[705144 rows x 3 columns]

In [51]:
df = filtered_df.assign(sortkey = filtered_df.groupby(["referral_source", "Signup_year", "Signup_month"])["Signup_month"].transform("count").sort_values(["sortkey", "referral_source", "Signup_year", "Signup_month"]), ascending = [False, True, False, True]).set_index(["referral_source", "Signup_year", "Signup_month"]).drop("sortkey", axis = 1)
df

TypeError: unhashable type: 'list'